-- CREAR LA DB Y USARLA
CREATE DATABASE WEBMART;
USE WEBMART;

-- CREAR LAS TABLAS
CREATE TABLE CATEGORIAS(
    ID_CAT TINYINT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    CONSTRAINT CATEGORIAS_PK PRIMARY KEY(ID_CAT)
);

CREATE TABLE SUBCATEGORIAS(
    ID_SUB SMALLINT AUTO_INCREMENT,
    ID_CAT TINYINT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    CONSTRAINT SUBCATEGORIAS_PK PRIMARY KEY(ID_SUB),
    CONSTRAINT SUBCATEGORIAS_FK FOREIGN KEY(ID_CAT) REFERENCES CATEGORIAS (ID_CAT)
);

CREATE TABLE USUARIOS(
    ID_USU SMALLINT AUTO_INCREMENT,
    USUARIO VARCHAR(30) NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(30),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR(30),
    DESCRIPCION VARCHAR(400),
    CORREO VARCHAR(40),
    DIRECCION VARCHAR(60),
    ICONO MEDIUMBLOB,
    ROL BOOLEAN NOT NULL,
    ESTADO BOOLEAN NOT NULL,
    CONSTRAINT USUARIOS_PK PRIMARY KEY(ID_USU),
    CONSTRAINT USUARIOS_UK UNIQUE(USUARIO),
    CONSTRAINT USUARIOS_UK2 UNIQUE(CORREO)
);

CREATE TABLE PRODUCTOS(
    ID_PROD MEDIUMINT AUTO_INCREMENT,
    ID_SUB SMALLINT NOT NULL,
    TITULO VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(500),
    PESO TINYINT,
    PRECIO DECIMAL(8,2) NOT NULL,
    FECHA_SUBIDA DATETIME,
    ID_RESERVA SMALLINT,
    ID_COMPRADOR SMALLINT,
    ID_USU SMALLINT NOT NULL,
    CONSTRAINT PRODUCTOS_FK FOREIGN KEY(ID_SUB) REFERENCES SUBCATEGORIAS(ID_SUB),
    CONSTRAINT PRODUCTOS_PK PRIMARY KEY(ID_PROD),
    CONSTRAINT PRODUCTOS_FK2 FOREIGN KEY(ID_RESERVA) REFERENCES USUARIOS(ID_USU),
    CONSTRAINT PRODUCTOS_FK3 FOREIGN KEY(ID_COMPRADOR) REFERENCES USUARIOS(ID_USU),
    CONSTRAINT PRODUCTOS_FK4 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE CONTRAS_ANTIGUAS(
    ID_CONTRA MEDIUMINT,
    ID_USU SMALLINT NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    CONSTRAINT CONTRAS_ANTIGUAS_PK PRIMARY KEY(ID_CONTRA),
    CONSTRAINT CONTRAS_ANTIGUAS_FK FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE RESERVAS(
    ID_PROD MEDIUMINT,
    ID_USU SMALLINT,
    CONSTRAINT RESERVAS_PK PRIMARY KEY(ID_USU,ID_PROD),
    CONSTRAINT RESERVAS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT RESERVAS_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE FAVORITOS(
    ID_PROD MEDIUMINT,
    ID_USU SMALLINT,
    CONSTRAINT FAVORITOS_PK PRIMARY KEY(ID_USU,ID_PROD),
    CONSTRAINT FAVORITOS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT FAVORITOS_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE FOTOS(
    ID_FOTO INT,
    ID_PROD MEDIUMINT NOT NULL,
    FOTO MEDIUMBLOB NOT NULL,
    CONSTRAINT FOTOS_PK PRIMARY KEY(ID_FOTO),
    CONSTRAINT FOTOS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD)
);

CREATE TABLE OPINIONES(
    ID_PROD MEDIUMINT,
    ID_USU SMALLINT,
    VALORACION TINYINT NOT NULL,
    MENSAJE VARCHAR(400) NOT NULL,
    CONSTRAINT OPINIONES_PK PRIMARY KEY(ID_PROD,ID_USU),
    CONSTRAINT OPINIONES_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT OPINIONES_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE CHATS(
    ID_CHAT MEDIUMINT,
    ID_PROD MEDIUMINT NOT NULL,
    ID_USU SMALLINT NOT NULL,
    ULTIMA_CONEX_PROD DATETIME NOT NULL,
    ULTIMA_CONEX_USU DATETIME NOT NULL,
    CONSTRAINT CHATS_PK PRIMARY KEY(ID_CHAT),
    CONSTRAINT CHATS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT CHATS_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE MENSAJES(
    ID_MENSAJE INT,
    ID_CHAT MEDIUMINT NOT NULL,
    ID_ENVIADOR SMALLINT NOT NULL,
    MENSAJE VARCHAR(400) NOT NULL,
    HORA DATETIME NOT NULL,
    CONSTRAINT MENSAJES_PK PRIMARY KEY(ID_MENSAJE),
    CONSTRAINT MENSAJES_FK FOREIGN KEY(ID_CHAT) REFERENCES CHATS(ID_CHAT),
    CONSTRAINT MENSAJES_FK2 FOREIGN KEY(ID_ENVIADOR) REFERENCES USUARIOS(ID_USU)
);

-- CREACION DE USUARIOS DE LA DB

-- W_ADMIN PRINCIPAL
CREATE USER WEBMART IDENTIFIED BY 'WebMart12345+';
CREATE USER WEBMART@localhost IDENTIFIED BY 'WebMart12345+';
GRANT ALL ON WEBMART.* TO WEBMART, WEBMART@localhost WITH GRANT OPTION;


-- USUARIO W_ADMIN PARA LA DB (USUARIOS ADMINS DE LA APP)
CREATE USER WEBMARTADMIN IDENTIFIED BY '12345+WebMartAdmin';
CREATE USER WEBMARTADMIN@localhost IDENTIFIED BY '12345+WebMartAdmin';
GRANT INSERT,DELETE,UPDATE,SELECT ON WEBMART.* TO WEBMARTADMIN, WEBMARTADMIN@localhost;


-- USUARIO NORMAL PARA LA DB (USUARIOS NORMALES DE LA APP)
CREATE USER WEBMARTUSER IDENTIFIED BY '12345+WebMartUser';
CREATE USER WEBMARTUSER@localhost IDENTIFIED BY '12345+WebMartUser';

-- PERMISOS PARA CADA TABLA:
-- SUBCATEGORIAS Y CATEGORIAS
GRANT SELECT ON WEBMART.CATEGORIAS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT SELECT ON WEBMART.SUBCATEGORIAS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- CHATS
GRANT SELECT,INSERT ON WEBMART.CHATS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (ULTIMA_CONEX_PROD,ULTIMA_CONEX_USU) ON WEBMART.CHATS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- CONTRAS_ANTIGUAS
GRANT SELECT,INSERT ON WEBMART.CONTRAS_ANTIGUAS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- FAVORITOS
GRANT SELECT,INSERT, DELETE ON WEBMART.FAVORITOS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- FOTOS
GRANT SELECT, INSERT, DELETE ON WEBMART.FOTOS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (FOTO) ON WEBMART.FOTOS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- MENSAJES
GRANT SELECT, INSERT ON WEBMART.MENSAJES TO WEBMARTUSER, WEBMARTUSER@localhost;

-- OPINIONES
GRANT SELECT, INSERT, DELETE ON WEBMART.OPINIONES TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (VALORACION,MENSAJE) ON WEBMART.OPINIONES TO WEBMARTUSER, WEBMARTUSER@localhost;

-- PRODUCTOS
GRANT SELECT, INSERT ON WEBMART.PRODUCTOS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (ID_SUB,TITULO,DESCRIPCION,PESO,PESO,ID_RESERVA,ID_COMPRADOR) ON WEBMART.PRODUCTOS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- RESERVAS
GRANT SELECT, INSERT, DELETE ON WEBMART.RESERVAS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- USUARIOS
GRANT INSERT, SELECT ON WEBMART.USUARIOS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (USUARIO,CONTRASEÑA,NOMBRE,APELLIDO1,APELLIDO2,ICONO,CORREO,DIRECCION) ON WEBMART.USUARIOS TO WEBMARTUSER, WEBMARTUSER@localhost;
FLUSH PRIVILEGES;

-- TABLA DE CATEGORIAS
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Motor');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Moda y Accesorios');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Hogar y Jardín');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('TV, Audio y Foto');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Telefonía');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Informática');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Inmobiliaria');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Empleo');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Formación y libros');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Servicios');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Juegos');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Videojuegos y Consolas');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Bebes');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Aficiones y Ocio');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Colecciones');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Deportes');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Mascota');
INSERT INTO CATEGORIAS(NOMBRE) VALUE('Otros');

-- TABLA DE SUBCATEGORÍAS
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Coches');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Motos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Caravanas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Furgonetas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Remolques');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Piezas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Accesorios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (1,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Camisas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Pantalones');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Camisetas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Sudaderas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Jerseys');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Chaquetas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Abrigos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Calzados');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Accesorios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (2,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Sillas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Mesas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Armarios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Sofas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Somieres');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Cajoes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Estanterias');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Amacas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Decoraciones');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Piscinas inchables');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Bricolaje');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (3,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Televisiones');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Altavoces');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Radios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Cámaras');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Proyectores');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Piezas / recambios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (4,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Smartphones');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Tablets');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Cargadores');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Fundas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Teléfonos fijo');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Fax');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (5,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Portátiles');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Ordenadores de sobremesa');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Impresoras');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Monitores');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Componentes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Periféricos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Software');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (6,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Alquiler/venta de viviendas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Alquiler/venta de locales');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Alquiler/venta de oficinas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Alquiler/venta de garajes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Alquiler/venta de trasteros');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Alquiler vacacional');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (7,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (8,'Necesidad de personal');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (8,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Clases particulares');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Autoescuela');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Cursos de idiomas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Libros');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Libros escolares');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Apuntes univerisatios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (9,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (10,'Para la persona');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (10,'Para el hogar');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (10,'Para el trabajo');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (10,'Para el motor');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (10,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (11,'Juguetes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (11,'Juegos de mesa');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (11,'Juegos de bar');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (11,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (12,'Videojuegos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (12,'Consolas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (12,'Mandos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (12,'Accsesorios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (12,'Productos exclusivos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (12,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Cunas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Tronas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Accesorios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Juguetes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Silla de paseo');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Cochecitos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Higiene y cuidado');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (13,'Otros');


INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Casa rural');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Puenting');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Airsoft');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Surf');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Montañismo');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Drones');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Caza');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Pesca');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Coches teledirigidos');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (14,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Cuadros');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Cartas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Dedales');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Monedas');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Billetes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Decoraciones');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (15,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (16,'Ropa deportiva');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (16,'Maquinaria deportiva');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (16,'Raquetas, balones, pelotas...');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (16,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (17,'Accesorios');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (17,'Higiene');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (17,'Comida');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (17,'Juguetes');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (17,'Servicios de cuidado');
INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (17,'Otros');

INSERT INTO SUBCATEGORIAS(ID_CAT, NOMBRE) VALUE (18,'Otro tipo de productos');
