-- CREAR LA DB Y USARLA
CREATE DATABASE WEBMART;
USE WEBMART;

-- CREAR LAS TABLAS

CREATE TABLE CATEGORIAS(
    ID_CAT TINYINT AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL,
    ICONO BLOB,
    CONSTRAINT CATEGIORIAS_PK PRIMARY KEY(ID_CAT)
);

CREATE TABLE USUARIOS(
    ID_USU SMALLINT AUTO_INCREMENT,
    USUARIO VARCHAR(30) NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(30),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR(30),
    DESCRIPCION VARCHAR(400),
    CORREO VARCHAR(40),
    DIRECCION VARCHAR(60),
    ROL BOOLEAN NOT NULL,
    ESTADO BOOLEAN NOT NULL,
    CONSTRAINT USUARIOS_PK PRIMARY KEY(ID_USU),
    CONSTRAINT USUARIOS_UK UNIQUE(USUARIO),
    CONSTRAINT USUARIOS_UK2 UNIQUE(CORREO)
);

CREATE TABLE PRODUCTOS(
    ID_CAT TINYINT NOT NULL,
    ID_PROD MEDIUMINT AUTO_INCREMENT,
    TITULO VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(500),
    PESO TINYINT,
    PRECIO DECIMAL(8,2) NOT NULL,
    FECHA_SUBIDA DATETIME,
    ID_RESERVA SMALLINT,
    ID_COMPRADOR SMALLINT,
    ID_USU SMALLINT NOT NULL,
    CONSTRAINT PRODUCTOS_FK FOREIGN KEY(ID_CAT) REFERENCES CATEGORIAS(ID_CAT),
    CONSTRAINT PRODUCTOS_PK PRIMARY KEY(ID_PROD),
    CONSTRAINT PRODUCTOS_FK2 FOREIGN KEY(ID_RESERVA) REFERENCES USUARIOS(ID_USU),
    CONSTRAINT PRODUCTOS_FK3 FOREIGN KEY(ID_COMPRADOR) REFERENCES USUARIOS(ID_USU),
    CONSTRAINT PRODUCTOS_FK4 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE CONTRAS_ANTIGUAS(
    ID_CONTRA MEDIUMINT,
    ID_USU SMALLINT NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    CONSTRAINT CONTRAS_ANTIGUAS_PK PRIMARY KEY(ID_CONTRA),
    CONSTRAINT CONTRAS_ANTIGUAS_FK FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE RESERVAS(
    ID_PROD MEDIUMINT,
    ID_USU SMALLINT,
    CONSTRAINT RESERVAS_PK PRIMARY KEY(ID_USU,ID_PROD),
    CONSTRAINT RESERVAS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT RESERVAS_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE FAVORITOS(
    ID_PROD MEDIUMINT,
    ID_USU SMALLINT,
    CONSTRAINT FAVORITOS_PK PRIMARY KEY(ID_USU,ID_PROD),
    CONSTRAINT FAVORITOS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT FAVORITOS_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE FOTOS(
    ID_FOTO INT,
    ID_PROD MEDIUMINT NOT NULL,
    FOTO BLOB NOT NULL,
    CONSTRAINT FOTOS_PK PRIMARY KEY(ID_FOTO),
    CONSTRAINT FOTOS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD)
);

CREATE TABLE OPINIONES(
    ID_PROD MEDIUMINT,
    ID_USU SMALLINT,
    VALORACION TINYINT NOT NULL,
    MENSAJE VARCHAR(400) NOT NULL,
    CONSTRAINT OPINIONES_PK PRIMARY KEY(ID_PROD,ID_USU),
    CONSTRAINT OPINIONES_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT OPINIONES_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE CHATS(
    ID_CHAT MEDIUMINT,
    ID_PROD MEDIUMINT NOT NULL,
    ID_USU SMALLINT NOT NULL,
    ULTIMA_CONEX_PROD DATETIME NOT NULL,
    ULTIMA_CONEX_USU DATETIME NOT NULL,
    CONSTRAINT CHATS_PK PRIMARY KEY(ID_CHAT),
    CONSTRAINT CHATS_FK FOREIGN KEY(ID_PROD) REFERENCES PRODUCTOS(ID_PROD),
    CONSTRAINT CHATS_FK2 FOREIGN KEY(ID_USU) REFERENCES USUARIOS(ID_USU)
);

CREATE TABLE MENSAJES(
    ID_MENSAJE INT,
    ID_CHAT MEDIUMINT NOT NULL,
    ID_ENVIADOR MEDIUMINT NOT NULL,
    MENSAJE VARCHAR(400) NOT NULL,
    HORA DATETIME NOT NULL,
    CONSTRAINT MENSAJES_PK PRIMARY KEY(ID_MENSAJE),
    CONSTRAINT MENSAJES_FK FOREIGN KEY(ID_CHAT) REFERENCES CHATS(ID_CHAT)
);

-- CREACION DE USUARIOS DE LA DB

-- ADMIN PRINCIPAL
CREATE USER WEBMART IDENTIFIED BY 'WebMart12345+';
CREATE USER WEBMART@localhost IDENTIFIED BY 'WebMart12345+';
GRANT ALL ON WEBMART.* TO WEBMART, WEBMART@localhost WITH GRANT OPTION;


-- USUARIO ADMIN PARA LA DB (UDUARIOS ADMINS DE LA APP)
CREATE USER WEBMARTADMIN IDENTIFIED BY '12345+WebMartAdmin';
CREATE USER WEBMARTADMIN@localhost IDENTIFIED BY '12345+WebMartAdmin';
GRANT INSERT,DELETE,UPDATE,SELECT ON WEBMART.* TO WEBMARTADMIN, WEBMARTADMIN@localhost;


-- USUARIO NORMAL PARA LA DB (USUARIOS NORMALES DE LA APP)
CREATE USER WEBMARTUSER IDENTIFIED BY '12345+WebMartUser';
CREATE USER WEBMARTUSER@localhost IDENTIFIED BY '12345+WebMartUser';
-- PERMISOS PARA CADA TABLA:
-- CATEGORIAS
GRANT SELECT ON WEBMART.CATEGORIAS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- CHATS
GRANT SELECT,INSERT ON WEBMART.CHATS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (ULTIMA_CONEX_PROD,ULTIMA_CONEX_USU) ON WEBMART.CHATS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- CONTRAS_ANTIGUAS
GRANT SELECT,INSERT ON WEBMART.CONTRAS_ANTIGUAS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- FAVORITOS
GRANT SELECT,INSERT, DELETE ON WEBMART.FAVORITOS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- FOTOS
GRANT SELECT, INSERT, DELETE ON WEBMART.FOTOS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (FOTO) ON WEBMART.FOTOS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- MENSAJES
GRANT SELECT, INSERT ON WEBMART.MENSAJES TO WEBMARTUSER, WEBMARTUSER@localhost;

-- OPINIONES
GRANT SELECT, INSERT, DELETE ON WEBMART.OPINIONES TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (VALORACION,MENSAJE) ON WEBMART.OPINIONES TO WEBMARTUSER, WEBMARTUSER@localhost;

-- PRODUCTOS
GRANT SELECT, INSERT ON WEBMART.PRODUCTOS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (ID_CAT,TITULO,DESCRIPCION,PESO,PESO,ID_RESERVA,ID_COMPRADOR) ON WEBMART.PRODUCTOS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- RESERVAS
GRANT SELECT, INSERT, DELETE ON WEBMART.RESERVAS TO WEBMARTUSER, WEBMARTUSER@localhost;

-- USUARIOS
GRANT INSERT, SELECT ON WEBMART.USUARIOS TO WEBMARTUSER, WEBMARTUSER@localhost;
GRANT UPDATE (USUARIO,CONTRASEÑA,NOMBRE,APELLIDO1,APELLIDO2,CORREO,DIRECCION) ON WEBMART.USUARIOS TO WEBMARTUSER, WEBMARTUSER@localhost;
FLUSH PRIVILEGES;





